### ISSUE TITLE
Goals for "Hello World" folder

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#16]
**Original**
1. ~explain the dependencies that would be required in the 'hello world' program~
2. ~provide a simple but clear hello world program that~
    - ~uses a few FP concepts~
    - ~has tests to verify it works correctly, thereby demonstrating how to write/structure tests using various libraries~
    - ~has benchmarks, thereby demonstrating how to benchmark one's code~
    - ~runs in both the Node environment and the web browser environment~

**Update 1:**
Ideally, the 'hello world' folder would 
1. Explain FP's philosophical foundations
2. Explain Prelude
3. Explain Eff/Effect (full) and Aff (somewhat)
4. Explain testing and benchmarking
5. Explain the various ways to structure an application
6. Provide exercises for the above via console-based games

**Comment by JordanMartinez** [comment]
## Prelude

### Context / Purpose

Since Prelude will be used everywhere, it should be explained well. However, since the library already exists, there's no need to reimplement the entire thing and deal with license issues. (I could just redirect to the source). Rather, this repo should serve as a guide for understanding it.

### Principles

- type classes are understood in isolation and in relation to one another (e.g. Functor, Apply, Monad, etc.)
- reuse existing documentation so as not to reinvent the wheel (e.g. charts already showing this kind of stuff / tutorial already explaining it.)

### Outcome

We'll need
- [x] a dependency graph indicating which type class one must understand first before understanding another (this should also include a % showing how often one uses such type classes)
- [x] a chart for the type signature comparisons (e.g. showing how `map` is similar to `apply`). **Done:** While there isn't a chart, I show the comparison in code
- [ ] laws for each type class explained by pictures

**Comment by JordanMartinez** [comment]
[This post](http://adit.io/posts/2013-04-17-functors,_applicatives,_and_monads_in_pictures.html) serves as a great start to making a picture-based explanation of frequently-used type classes (e.g. Functor, Apply, Monad).

**Comment by JordanMartinez** [comment]
[This slide from a recent Purescript video](https://youtu.be/EoJ9xnzG76M?t=7m9s) gives a bit less noisy explanation for Monad laws.

**Comment by JordanMartinez** [comment]
[This link](https://sras.me/haskell/miscellaneous-enlightenments.html) explains some things that would be helpful to remember when explaining things / use to update some of this project's work

**Comment by JordanMartinez** [comment]
[Another link](https://steven741.github.io/posts/2018-07-28-haskell-tutorial-1.html)

**Comment by JordanMartinez** [comment]
[This article](https://medium.com/axiomzenteam/functor-applicative-and-why-8a08f1048d3d) explains data validation via Applicatives

**Comment by JordanMartinez** [comment]
I'll need to document `Effect` and how it works / what it does since [the corresponding page on PS' documentation repo](https://github.com/purescript/documentation/blob/master/guides/Eff.md) is outdated.

**Comment by JordanMartinez** [comment]
This folder should include a link to [the Style Guide](https://github.com/purescript/documentation/blob/master/guides/Style-Guide.md)

**Comment by JordanMartinez** [comment]
Rather than using `benchotron`, I could use `minibench`: https://pursuit.purescript.org/packages/purescript-minibench/2.0.0

**Comment by JordanMartinez** [comment]
I think another goal of this project should be to explain `Tagless Final` as quickly and concisely as possible.

**Comment by JordanMartinez** [comment]
This folder should also document how to create custom type errors

**Comment by JordanMartinez** [comment]
And document how to handle errors

**Comment by JordanMartinez** [comment]
There seems to be a number of different ports of QuickCheck to Purescript, that I'm not entirely sure which should be used:
- [purescript-quickcheck](https://github.com/purescript/purescript-quickcheck) - Basic QuickCheck; used in `purescript-quickcheck-laws`
- [purescript-strongcheck](https://github.com/purescript-contrib/purescript-strongcheck) - Basic QuickCheck + exhaustive testing + statistics
- [jack](https://github.com/jystic/purescript-jack) - QuickCheck + shrinking - Arbitrary (inactive?)
- [purescript-properties](https://github.com/Risto-Stevcev/purescript-properties) - properties for usage across all test libraries

[purescript-test-unit](https://github.com/bodil/purescript-test-unit) is also available, but is just another unit testing library.

**Comment by JordanMartinez** [comment]
Since my previous comment, I've written code that explains the basic ideas of MTL (#58) and Free/Run (#68), culminating in the Onion Architecture idea. I've also written a random-number-guessing game using this architecture via a Run-based DSL that includes a QuickCheck test to insure my game logic works correctly given a valid interpreter.

However, I have not yet done the same work using MTL. For now, I think I'll continue on and get back to it later.

My next focus should be on learning Type-Level Programming, so that I can understand how libraries like `purescript-run` and `purescript-variant` actually work.

**Comment by JordanMartinez** [comment]
I think the "Hello World" folder is more or less finished. There are a few things I can edit or make flow better, but content-wise I think it is good enough.
