### ISSUE TITLE
Upgrade repo to 0.12.2

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#218]
Waiting on its release, but it'll be soon, so I'm filing it here.

Things I'll need to do to update this fully besides upgrading all projects to a newer package set:
- [x] change the project's ReadMe to indicate it now works for `0.12.2` release
- [x] update Boolean kind to use Prim.Boolean
- [x] update any mention of non-Prim built-in types/kinds to doc repo
- [x] Update REPL part to mention multiple command types in paste-mode
- [x] Remove any mention of "please manually import these in the REPL before copy-pasting the rest of file"
- [x] Explain the new ":print" REPL command
- [x] Explain rebindable `do`/`ado` syntax
- [x] Explain that reserved PS keywords can be used as labels in rows without wrapping them in quotes

**Comment by JordanMartinez** [comment]
The release has been made. I'm just waiting for the NPM package to be updated, too.

**Comment by JordanMartinez** [comment]
NPM package for `purescript` has been updated. However, Pursuit doesn't yet show the new `Prim.Boolean` module... :-/

**Comment by JordanMartinez** [comment]
Waiting on purescript/pursuit#385

**Comment by JordanMartinez** [comment]
Other context for 'rebindable do/ado' syntax:

> Also, what are the conditions one needs to satisfy before they can use the rebindable do/ado syntax?

> You have to have a module that exports bind and discard for do, and apply and pure for ado

> Ok, good to know. Does the type signatures for those functions matter at all?

> It has to fit the shape of the desugaring, but it doesn’t have to carry a Monad constraint or anything

> Ok. I think I understand enough to explain it now.

**Comment by JordanMartinez** [comment]
Great. Everything here is ready to go.
