### ISSUE TITLE
Update project to 0.12.3

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#269]
Release notes: https://github.com/purescript/purescript/releases/tag/v0.12.3

Tasks:
- [x] Remove the `ado breaks docs` warning in the Syntax folder
- [x] Update ReadMe to state that this project uses 0.12.3
- [x] Update version used in installation instructions
- [x] Update version used in CI

Pretty simple and painless update.

**Comment by JordanMartinez** [comment]
Closed by #284
