### ISSUE TITLE
Update project in light of 0.15.0 release

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#582]
There's a number of things to update in this repo:
- [x] add section on type-level integers (work done in `development` branch)
- [x] add/update section on FFI
- [x] remove `purs bundle` references
- [x] add section on `esbuild`
- [x] add section on `Reflectable` type class
- [x] update code so that it still compiles

**Comment by jsomedon** [comment]
I was just about to open an issue and I saw this.. looking forward for the update for 0.15 😄

**Comment by JordanMartinez** [comment]
Yeah, I need to see how much of the code compiles right now. I think I'm still waiting for the next package set release, but I haven't actually explored this to see what works / doesn't work.

**Comment by JordanMartinez** [comment]
I've pushed a few commits to `development`. I'll have to work on this more later today.

**Comment by JordanMartinez** [comment]
@jsomedon It's now live: https://jordanmartinez.github.io/purescript-jordans-reference-site/
